# Site settings
title: Eu Amo Vida
description: Amar jamais será demais!
baseurl: "" # the subpath of your site, e.g. /blog
url: "euamovida.com"

# User settings
# username: Eu Amo Vida
user_description: Amar jamais será demais!
user_title: Eu Amo Vida
email: projetoeuamovida@gmail.com
twitter_username: projeuamovida
github_username:  euamovida
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
