# Site settings
title: Eu Amo Vida
description: "Por onde for... A toda vida doe amor!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.euamovida.com"

# User settings
# username: Eu Amo Vida
user_description: Por onde for... A toda vida doe amor!
user_title: Eu Amo Vida
email: projetoeuamovida@gmail.com
twitter_username: projeuamovida
facebook:  projetoeuamovida
instagram: projetoeuamovida
youtube: UCdw2AwXnDpZsEGDx0rasxlQ

# Google-analytics
google-analytics:
  id: "UA-141590432-1"

permalink: /:title

plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude: ['package.json', 'src' , 'node_modules']
