# Site settings
title: Eu Amo Vida
description: Amar jamais será demais!
baseurl: "" # the subpath of your site, e.g. /blog
url: "euamovida.com"

# User settings
# username: Eu Amo Vida
user_description: Amar jamais será demais!
user_title: Eu Amo Vida
email: projetoeuamovida@gmail.com
twitter_username: projeuamovida
facebook:  projetoeuamovida
instagram: projetoeuamovida

# Google-analytics
google-analytics:
  id: ""

plugins:
  - jekyll-seo-tag

exclude: ['package.json', 'src' , 'node_modules']
